[package]
name = "drizzle-macros"
version = "0.1.2"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0.37" }
proc-macro2 = { version = "1.0.89" }
syn = { version = "2.0.87", features = ["full"] }
rand = { version = "0.8.5" }
heck = { version = "0.5.0" }
proc-macro-crate = "3.3.0"
paste = { workspace = true }

[features]
default = []
serde = []
sqlite = []
postgres = []
mysql = []
uuid = []
# PostgreSQL optional type features
chrono = []
rust_decimal = []
ipnet = []
geo-types = []
bitvec = []
rusqlite = ["sqlite"]
libsql = ["sqlite"]
turso = ["sqlite"]
# sqlx-postgres = ["postgres"]
